version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  groups:
    codeql:
      patterns:
        - "github/codeql-action/*"
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: weekly
