title: Shy Ramblings
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Yet another site Randall does not maintain.
subtitle: Yet another site Randall does not maintain.
baseurl: ""
url: https://rhwood.github.io
minimal_mistakes_skin: default
locale: en-US
breadcrumbs: true
show_date: true
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/rhwood

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
