name: CI Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Jekyll warnings
        run: bundle exec jekyll doctor
      - name: Test links
        # Ignore 302 (redirects), 403 (forbidden), 406 (not acceptable), 418 (I'm a teapot), and 999 (LinkedIn's "bot detected" status code)
        # Manual testing should not ignore these status codes, but for automated testing, we want to avoid false positives from sites that block bots or have temporary redirects.
        run: bundle exec htmlproofer --ignore-status-codes "302,403,406,418,999" ./_site
